app:
  label: demo-app

deployment:
  name: demo-app-deployment
  replicas: 2
  strategy:
    maxSurge: 25%         
    maxUnavailable: 25%

image:
  repository: 381492123981.dkr.ecr.us-east-1.amazonaws.com/demo-app
  tag: v1.0.23
  containerPort: 3000

imagePullSecrets:
  - name: ecr-creds

service:
  name: demo-app-service
  type: ClusterIP  
  port: 80
  targetPort: 3000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75

ingress:
  create: true  
  className: nginx  
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: demoapp.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: demo-app-tls
     hosts:
       - demoapp.com
