apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
  labels:
    app: {{.Values.app.label}}
spec:
  replicas: {{.Values.deployment.replicas}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{.Values.deployment.strategy.maxSurge}}
      maxUnavailable: {{.Values.deployment.strategy.maxUnavailable}}
  selector:
    matchLabels:
      app: {{.Values.app.label}}
  template:
    metadata:
      labels:
        app: {{.Values.app.label}}
    spec:
      imagePullSecrets:
        - name: {{index .Values.imagePullSecrets 0 "name"}}
      containers:
        - name: {{.Values.app.label}}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          ports:
            - containerPort: {{.Values.image.containerPort}}
